In [1]:
import numpy as np

In [2]:
Efields = np.append(np.arange(0,100,20),np.arange(100,410,50))
print(len(Efields))
Efields

12


array([  0,  20,  40,  60,  80, 100, 150, 200, 250, 300, 350, 400])

In [3]:
pre1 = np.array([0.5])
Pressure = np.append(pre1,np.arange(1,12,2))*750
Pressure = [int(Input) for Input in Pressure]
print(len(Pressure))
Pressure

7


[375, 750, 2250, 3750, 5250, 6750, 8250]

In [4]:
Fractions = np.arange(0,101,5)
print(len(Fractions))
FractionsAr = Fractions
FractionsAr

21


array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [5]:
FractionsXe = 100-Fractions
FractionsXe

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5,   0])

In [6]:
def CardGen(Pressure, Efield, XePer, ArPer):
    NGAS   = 2
    NMAX   = 2
    IPEN   = 0
    ITHERM = 1
    EFINAL = 0.0
    NGAS1  = 7
    NGAS2  = 2
    NGAS3  = 0
    NGAS4  = 0
    NGAS5  = 0
    NGAS6  = 0
    FRAC1  = XePer
    FRAC2  = ArPer
    FRAC3  = 0
    FRAC4  = 0
    FRAC5  = 0
    FRAC6  = 0
    TEMP   = 23
    TORR   = Pressure
    EFIELD = Efield
    BMAG   = 0
    BTHETA = 0
    TERM   = 4*NGAS+1

    InputCard = [NGAS,  NMAX,  IPEN,   ITHERM, EFINAL,
                 NGAS1, NGAS2, NGAS3,  NGAS4,  NGAS5,  NGAS6,
                 FRAC1, FRAC2, FRAC3,  FRAC4,  FRAC5,  FRAC6,
                 TEMP,  TORR,  EFIELD, BMAG,   BTHETA, TERM ] 

    InputCard = [str(Input) for Input in InputCard]
    Xe  = str(XePer).zfill(3)
    Ar  = str(ArPer).zfill(3)
    P = str(Pressure).zfill(4)
    E   = str(Efield).zfill(3)
    FileName  = "Xe-"+Xe+"_Ar-"+Ar+"_P-"+P+"_E-"+E+"_.txt"
    ScriptName  = "Xe-"+Xe+"_Ar-"+Ar+"_P-"+P+"_E-"+E+"_.sh"
    return InputCard , FileName, ScriptName
    

In [20]:
FractionsAr = np.array([97.994, 91.863, 84.747, 64.432, 0.953])
FractionsEr = np.array([ 0.575, 0.417, 0.344, 0.216, 0.121])

In [21]:
FAR = FractionsAr+FractionsEr
FAR = np.append(FAR,FractionsAr-FractionsEr)
100-FAR

array([  1.431,   7.72 ,  14.909,  35.352,  98.926,   2.581,   8.554,
        15.597,  35.784,  99.168])

In [22]:
FAR = FractionsAr#+FractionsEr
FAR = np.append(FAR,FractionsAr)#-FractionsEr)
100-FAR

array([  2.006,   8.137,  15.253,  35.568,  99.047,   2.006,   8.137,
        15.253,  35.568,  99.047])

In [9]:
FArUP = FractionsAr+FractionsEr
FXeup = 100-FArUP

In [16]:
Card, Fname, ScrName = CardGen(10,200,FXeup[4],100-FXeup[4])

In [17]:
Fname

'Xe-98.926_Ar-1.074_P-0010_E-200_.txt'

In [14]:
FXeup[0]

1.4309999999999974

In [88]:
def InputFileGen(Card,Path,Name):
    FullPath = Path+Name
    File = open(FullPath,'a')
    for Input in Card:
        File.write(Input)
        File.write("\n")
    File.close()

In [92]:
def ScriptGen(ScrPath, ScrName,MagPath, InputPath, OutPath, Fname):
    SCPath = ScrPath+ScrName
    InPath   = InputPath+Fname
    OutPath  = OutPath+Fname
    File = open(SCPath,'a')
    File.write("#!/bin/sh"+"\n")
    File.write("#PBS -q hep"+"\n")
    File.write("#PBS -l nodes=1 "+"\n")
    File.write("#PBS -l cput=00:30:00  "+"\n")
    File.write("#PBS -m bea"+"\n")
    File.write("#PBS -M austin.mcdonald@uta.edu"+"\n")
    File.write("\n")
    File.write(MagPath+" < "+InPath+" > "+OutPath)
    File.close()

In [95]:
PATH      = "/Users/austinmcdonald/Desktop/TestIN/"
MagPath   = '/cluster/home/amcdonald/Gas-Physics/a.out'
InputPath = '/Users/austinmcdonald/Desktop/TestIN/Input/'
OutPath   = '/Users/austinmcdonald/Desktop/TestIN/Output/'
ScrPath   = '/Users/austinmcdonald/Desktop/TestIN/Script/'
for P in Pressure:
    for E in Efields:
        for FXe in FractionsXe:
            Card, Fname, ScrName = CardGen(P,E,FXe,100-FXe)
            InputFileGen(Card, InputPath, Fname)
            ScriptGen(ScrPath, ScrName,MagPath, InputPath, OutPath, Fname)
        

In [68]:
MagPath = '/cluster/home/amcdonald/Gas-Physics/a.out'
InputPath = '/cluster/home/amcdonald/Gas-Physics/inputTest.txt'
OutPath  = '/cluster/home/amcdonald/Gas-Physics/Outputs/Test2.txt'
def ScriptGen(ScrPath, ScrName,MagPath, InputPath, OutPath, Fname):
    FullPath = ScrPath+ScrName
    InPath   = InputPath+Fname
    OutPath  = OutPath+Fname
    File = open(FullPath,'a')
    File.write("#!/bin/sh"+"\n")
    File.write("#PBS -q hep"+"\n")
    File.write("#PBS -l nodes=1 "+"\n")
    File.write("#PBS -l cput=00:30:00  "+"\n")
    File.write("#PBS -m bea"+"\n")
    File.write("#PBS -M austin.mcdonald@uta.edu"+"\n")
    File.write("\n")
    File.write(MagPath+" < "+InPath+" > "+OutPath)
    File.close()

In [65]:
PATH = "/Users/austinmcdonald/Desktop/TestIN/"
ScriptGen(PATH, 'Test.sh',MagPath, InputPath, OutPath)

In [ ]:
#!/bin/sh                                                                                                                                                           
#PBS -q hep                                                                                                                                                         
#PBS -l nodes=1                                                                                                                                                     
#PBS -l cput=00:30:00                                                                                                                                               
#PBS -m bea                                                                                                                                                         
#PBS -M austin.mcdonald@uta.edu                                                                                                                                     


/cluster/home/amcdonald/Gas-Physics/a.out < /cluster/home/amcdonald/Gas-Physics/inputTest.txt > /cluster/home/amcdonald/Gas-Physics/Outputs/Test2.txt




In [52]:
Card, Fname = CardGen(Pressure[6],Efields[0],FractionsXe[0],FractionsAr[0])

In [ ]:
def InputFile(Card,Path,Name):
    FullPath = Path+Name
    File = open(FullPath,'a')
    for Input in Card:
        File.write(Input)
        File.write("\n")
    File.close()

In [ ]:
/Users/austinmcdonald/Desktop/TestIN

In [ ]:
F = open("/Users/austinmcdonald/Desktop/TTest.txt",'a')
for Input in InputCard:
    F.write(Input)
    F.write("\n")
F.close()

In [7]:
NGAS   = 2
NMAX   = 2
IPEN   = 0
ITHERM = 1
EFINAL = 0.0
NGAS1  = 7
NGAS2  = 2
NGAS3  = 0
NGAS4  = 0
NGAS5  = 0
NGAS6  = 0
FRAC1  = 97
FRAC2  = 3
FRAC3  = 0
FRAC4  = 0
FRAC5  = 0
FRAC6  = 0
TEMP   = 23
TORR   = 750
EFIELD = 200
BMAG   = 0
BTHETA = 0
TERM   = 4*NGAS+1

InputCard = [NGAS,  NMAX,  IPEN,   ITHERM, EFINAL,
             NGAS1, NGAS2, NGAS3,  NGAS4,  NGAS5,  NGAS6,
             FRAC1, FRAC2, FRAC3,  FRAC4,  FRAC5,  FRAC6,
             TEMP,  TORR,  EFIELD, BMAG,   BTHETA, TERM ] 

InputCard = [str(Input) for Input in InputCard]

In [8]:
InputCard = [str(Input) for Input in InputCard]

In [9]:
F = open("/Users/austinmcdonald/Desktop/TTest.txt",'a')
for Input in InputCard:
    F.write(Input)
    F.write("\n")
F.close()

In [14]:
5000/13.8

362.3188405797101

In [8]:
InputCardStr = [str(Input) for Input in InputCard]

In [9]:
InputCardStr

['2',
 '2',
 '0',
 '1',
 '0.0',
 '7',
 '2',
 '0',
 '0',
 '0',
 '0',
 '97',
 '3',
 '0',
 '0',
 '0',
 '0',
 '23',
 '750',
 '200',
 '0',
 '0',
 '9']

In [13]:
a=[]
for Input in InputCardStr:
    a.append(Input.encode())

In [14]:
a

[b'2',
 b'2',
 b'0',
 b'1',
 b'0.0',
 b'7',
 b'2',
 b'0',
 b'0',
 b'0',
 b'0',
 b'97',
 b'3',
 b'0',
 b'0',
 b'0',
 b'0',
 b'23',
 b'750',
 b'200',
 b'0',
 b'0',
 b'9']

In [15]:
import numpy as np

In [21]:
D1 = 1.58
D2 = 13.8
D3 = 0.397

Drift_Field = np.linspace(10,500,50)
Vbias_Drift = Drift_Field*D2
Vbial_Plate = 2*Drift_Field*D1
Vbias_Gold  = Vbias_Drift + 300*D3

In [31]:
Run = 29
print("Drift field of ", Drift_Field[Run])
print("Gold Bias of " , Vbias_Gold[Run])
print("Drift Bias of ", Vbias_Drift[Run])
print("Plate Bias of ", Vbial_Plate[Run])
print()
print("Reduced field of ",Drift_Field[Run]/11)

Drift field of  300.0
Gold Bias of  4259.1
Drift Bias of  4140.0
Plate Bias of  948.0

Reduced field of  27.2727272727


In [32]:
Run = 24
print("Drift field of ", Drift_Field[Run])
print("Gold Bias of " , Vbias_Gold[Run])
print("Drift Bias of ", Vbias_Drift[Run])
print("Plate Bias of ", Vbial_Plate[Run])
print()
print("Reduced field of ",Drift_Field[Run]/11)

Drift field of  250.0
Gold Bias of  3569.1
Drift Bias of  3450.0
Plate Bias of  790.0

Reduced field of  22.7272727273


In [33]:
Run = 19
print("Drift field of ", Drift_Field[Run])
print("Gold Bias of " , Vbias_Gold[Run])
print("Drift Bias of ", Vbias_Drift[Run])
print("Plate Bias of ", Vbial_Plate[Run])
print()
print("Reduced field of ",Drift_Field[Run]/11)

Drift field of  200.0
Gold Bias of  2879.1
Drift Bias of  2760.0
Plate Bias of  632.0

Reduced field of  18.1818181818


In [35]:
Run = 14
print("Drift field of ", Drift_Field[Run])
print("Gold Bias of " , Vbias_Gold[Run])
print("Drift Bias of ", Vbias_Drift[Run])
print("Plate Bias of ", Vbial_Plate[Run])
print()
print("Reduced field of ",Drift_Field[Run]/11)

Drift field of  150.0
Gold Bias of  2189.1
Drift Bias of  2070.0
Plate Bias of  474.0

Reduced field of  13.6363636364


In [36]:
Run = 9
print("Drift field of ", Drift_Field[Run])
print("Gold Bias of " , Vbias_Gold[Run])
print("Drift Bias of ", Vbias_Drift[Run])
print("Plate Bias of ", Vbial_Plate[Run])
print()
print("Reduced field of ",Drift_Field[Run]/11)

Drift field of  100.0
Gold Bias of  1499.1
Drift Bias of  1380.0
Plate Bias of  316.0

Reduced field of  9.09090909091


In [39]:
Run = 
print("Drift field of ", Drift_Field[Run])
print("Gold Bias of " , Vbias_Gold[Run])
print("Drift Bias of ", Vbias_Drift[Run])
print("Plate Bias of ", Vbial_Plate[Run])
print()
print("Reduced field of ",Drift_Field[Run]/11)

Drift field of  50.0
Gold Bias of  809.1
Drift Bias of  690.0
Plate Bias of  158.0

Reduced field of  4.54545454545
